// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Restaurant struct {
	ID           uuid.UUID
	OsmID        string
	Name         string
	Kind         string
	Cuisines     []string
	Street       string
	Housenumber  string
	Postcode     string
	City         string
	Website      string
	Phone        string
	OpeningHours string
	Lat          float64
	Lon          float64
	CreatedAt    pgtype.Timestamptz
	ModifiedAt   pgtype.Timestamptz
}
