// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restaurants.sql

package database

import (
	"context"

	"uuid"
)

const listRestaurants = `-- name: ListRestaurants :many
SELECT id, name, kind, cuisines, street, housenumber, 
    postcode, city, website, phone, opening_hours
FROM restaurants
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListRestaurantsParams struct {
	Cursor   uuid.UUID
	RowLimit int32
}

type ListRestaurantsRow struct {
	ID           uuid.UUID
	Name         string
	Kind         string
	Cuisines     []string
	Street       string
	Housenumber  string
	Postcode     string
	City         string
	Website      string
	Phone        string
	OpeningHours string
}

func (q *Queries) ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]ListRestaurantsRow, error) {
	rows, err := q.db.Query(ctx, listRestaurants, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRestaurantsRow
	for rows.Next() {
		var i ListRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Cuisines,
			&i.Street,
			&i.Housenumber,
			&i.Postcode,
			&i.City,
			&i.Website,
			&i.Phone,
			&i.OpeningHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
